apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qh3zwwvov-go
  janus-idp.io/tekton: qh3zwwvov-go
  backstage.io/kubernetes-id: qh3zwwvov-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qh3zwwvov-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
