apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qh3zwwvov-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qh3zwwvov-go 
  name: qh3zwwvov-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qh3zwwvov-go 
